---
{{- if .Values.additionalConfigmap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.additionalConfigmap.name }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data: {{- toYaml .Values.additionalConfigmap.data | nindent 2 }}
{{- end }}
