name: On Tag Push Charts to helm-charts-registry

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

concurrency:
  group: infra-sshd-chart
  cancel-in-progress: true

jobs:
  scan:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@7
    permissions:
      contents: read
  release:
    needs: scan
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@7
    secrets: inherit
    with:
      chart_path: .
      chart_name: infra-sshd
      helm_chart_version_generation: specified
      image_tag_generation: chart_yaml
      helm_chart_version: ${{ github.ref_name }}