name: Push Chart to helm-charts-registry
on:
  push:
    branches-ignore:
      - 'main'

concurrency:
  group: infra-sshd-chart
  cancel-in-progress: true

jobs:
  scan:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/check-helm-kics.yaml@7
    permissions:
      contents: read
  release_helm:
    uses: dBildungsplattform/dbp-github-workflows/.github/workflows/chart-release.yaml@7
    secrets: inherit
    with:
      chart_name: infra-sshd
      helm_chart_version_generation: ticket_from_branch_timestamp
      image_tag_generation: chart_yaml
